name: Best Practices Tests
'on':
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    name: Action Test
    steps:
      - uses: saucelabs/sauce-connect-action@v2
        with:
          username: '${{ secrets.SAUCE_USERNAME }}'
          accessKey: '${{ secrets.SAUCE_ACCESS_KEY }}'
          region: us-west
          tunnelName: test_tunnel_name
          # configFile: ${{ github.workspace }}/sc-configuration/config.yaml
